import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/utils/cn';
import { ThemeProvider } from 'next-themes';
import Image from 'next/image';
import { UserDropdown } from '@/components/user-dropdown';

const inter = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body className={cn(inter.variable, 'antialiased font-sans')}>
				<ThemeProvider>
					<header className='px-6 py-3 border-b flex items-center gap-3'>
						<Image
							src={
								'https://images.mlssoccer.com/image/upload/t_q-best/v1736287039/assets/sdn/logos/sd_logo_pri_fc_rgb_480x480__1__720_1_jlm4tx.png'
							}
							alt='San Diego FC Logo'
							width={50}
							height={50}
							className='object-contain'
						/>

						<h1 className='text-title-h4 font-bold'>Culture and Performance Weekly Survey</h1>

						<UserDropdown />
					</header>

					<main className='p-6 h-screen'>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
